name: flutter_appkit
description: Production-ready runtime and infrastructure support for Flutter apps — error handling, logging, locale, context, Riverpod, and more.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.8.1
homepage: https://github.com/piyuo/flutter-appkit/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sentry_flutter: ^9.29.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.4.2 # block by analyzer
  riverpod_annotation: ^4.0.6 # block by analyzer
  talker: ^5.1.20
  talker_flutter: ^5.1.20
  talker_riverpod_logger: ^5.1.20
  flutter_dotenv: ^6.0.1
  universal_io: ^2.3.1
  liquid_glass_widgets: ^1.2.3
dev_dependencies:
  analyzer: ^13.3.0 # block by test
  sentry_dart_plugin: ^3.4.0
  build_runner: ^2.16.0
  flutter_test:
    sdk: flutter
  mockito: ^5.8.1 # block by analyzer
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.8 # block by analyzer


# The following section is specific to Flutter.
flutter:
    generate: true
    uses-material-design: true
    # To add assets to your package, add an assets section, like this:
    #assets:
    #- .env.test
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: piyuo